---
- name: Deploy Application
  hosts: ansible-server 
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Ensure application directory exists
      file:
        path: /home/ubuntu/python-app
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy application files
      copy:
        src:  /
        dest: /opt/my-app/
        owner: ubuntu
        group: ubuntu

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install Python requirements
      pip:
        requirements: /opt/my-app/requirements.txt

    - name: Restart application service
      systemd:
        name: my-app
        state: restarted
        enabled: yes
