---
- name: Deploy Application
  hosts: ansible-server 
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Ensure application directory exists
      file:
        path: /home/ubuntu/python-app
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install Python requirements
      pip:
        requirements: /home/ubuntu/python-app/Python-Sample-Application/requirements.txt

    - name: Restart application service
      systemd:
        name: python-app
        state: restarted
        enabled: yes
