---
- name: Web server setup on Ubuntu
  hosts: webserver1 
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update the system packages
      apt: 
        update_cache: yes 

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Deploy a simple web page
      copy:
        content: |
          <html>
          <head>
              <title>Welcome to My Web Server</title>
          </head>
          <body>
              <h1>Hello!</h1>
          </body>
          </html>
        dest: /var/www/html/index.html

- name: Web server setup on Amazon Linux
  hosts: webserver2
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Update the system packages
      yum:
        update_cache: yes
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: start and enable Nginx
      service:
        name: nginx
        state: started

    - name: Deploy a simple web page
      copy:
        content: |
          <head>
              <title>Welcome to My Web Server</title>
          </head>
          <body>
              <h1>Hello from Ansible!</h1>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html

...